server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/vscode/spring-cloud/native-file-repo
        git:
#          uri: file:///home/tony/vscode/spring-cloud/git-local-repo
          uri: https://github.com/kuuku123/spring-cloud-config
        default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
